Clear DESTDIR to avoid build error due to openssl location
...
  install ./include/openssl/x509err.h -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/include/openssl/x509err.h
  install ./include/openssl/x509v3.h -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/include/openssl/x509v3.h
  install ./include/openssl/x509v3err.h -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/include/openssl/x509v3err.h
  install libcrypto.a -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/libcrypto.a
  install libssl.a -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/libssl.a
  created directory `/mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/pkgconfig'
  install exporters/libcrypto.pc -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/pkgconfig/libcrypto.pc
  install exporters/libssl.pc -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/pkgconfig/libssl.pc
  install exporters/openssl.pc -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/pkgconfig/openssl.pc
  created directory `/mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/cmake'
  created directory `/mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/cmake/OpenSSL'
  install exporters/OpenSSLConfig.cmake -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/cmake/OpenSSL/OpenSSLConfig.cmake
  install exporters/OpenSSLConfigVersion.cmake -> /mnt/kata-containers/tools/packaging/kata-deploy/local-build/build/shim-v2/destdir/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/cmake/OpenSSL/OpenSSLConfigVersion.cmake
  make[1]: Leaving directory '/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src'
  cargo:vendored=1
  cargo:root=/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install

  --- stderr
  DEBUG: all keys: APPLINKDIR, BINDIR, CMAKECONFIGDIR, ENGINESDIR, INCLUDEDIR, LDLIBS, LIBDIR, MODULESDIR, PKGCONFIGDIR, PREFIX, VERSION, libdir
  No value given for CMAKECONFIGDIR
  No value given for PKGCONFIGDIR
  No value given for libdir
  DEBUG: PREFIX = . => PREFIX = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src
  DEBUG: libdir = . => libdir = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src
  DEBUG: BINDIR = apps => BINDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src/apps, BINDIR_REL_PREFIX = apps
  DEBUG: LIBDIR =  => LIBDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src, LIBDIR_REL_PREFIX =
  DEBUG: INCLUDEDIR = [ include, ./include ] => INCLUDEDIR = [ /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src/include, /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src/include ], INCLUDEDIR_REL_PREFIX = [ include, ./include ]
  DEBUG: APPLINKDIR = ms => APPLINKDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src/ms, APPLINKDIR_REL_PREFIX = ms
  DEBUG: ENGINESDIR = engines => ENGINESDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src/engines, ENGINESDIR_REL_LIBDIR = engines
  DEBUG: MODULESDIR = providers => MODULESDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src/providers, MODULESDIR_REL_LIBDIR = providers
  DEBUG: PKGCONFIGDIR = . => PKGCONFIGDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src, PKGCONFIGDIR_REL_LIBDIR = .
  DEBUG: CMAKECONFIGDIR = . => CMAKECONFIGDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/build/src, CMAKECONFIGDIR_REL_LIBDIR = .
  DEBUG: all keys: APPLINKDIR, BINDIR, CMAKECONFIGDIR, ENGINESDIR, INCLUDEDIR, LDLIBS, LIBDIR, MODULESDIR, PKGCONFIGDIR, PREFIX, VERSION, libdir
  DEBUG: PREFIX = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install => PREFIX = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install
  DEBUG: libdir = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib => libdir = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib
  DEBUG: BINDIR = bin => BINDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/bin, BINDIR_REL_PREFIX = bin
  DEBUG: LIBDIR = lib => LIBDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib, LIBDIR_REL_PREFIX = lib
  DEBUG: INCLUDEDIR = include => INCLUDEDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/include, INCLUDEDIR_REL_PREFIX = include
  DEBUG: APPLINKDIR = include/openssl => APPLINKDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/include/openssl, APPLINKDIR_REL_PREFIX = include/openssl
  DEBUG: ENGINESDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/engines-3 => ENGINESDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/engines-3, ENGINESDIR_REL_LIBDIR = engines-3
  DEBUG: MODULESDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/ossl-modules => MODULESDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/bu
ild/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/ossl-modules, MODULESDIR_REL_LIBDIR = ossl-modules
  DEBUG: PKGCONFIGDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/pkgconfig => PKGCONFIGDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/pkgconfig, PKGCONFIGDIR_REL_LIBDIR = pkgconfig
  DEBUG: CMAKECONFIGDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/cmake/OpenSSL => CMAKECONFIGDIR = /mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib/cmake/OpenSSL, CMAKECONFIGDIR_REL_LIBDIR = cmake/OpenSSL

  thread 'main' panicked at /opt/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openssl-sys-0.9.109/build/main.rs:189:9:
  OpenSSL library directory does not exist: ["/mnt/kata-containers/src/runtime-rs/target/x86_64-unknown-linux-musl/release/build/openssl-sys-c408673f0de4c4ee/out/openssl-build/install/lib"]
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:661: target/x86_64-unknown-linux-musl/release/containerd-shim-kata-v2] Error 101
make[1]: *** [tools/packaging/kata-deploy/local-build/Makefile:93: shim-v2-tarball-build] Error 2
make[1]: Leaving directory '/mnt/kata-containers'
make: *** [tools/packaging/kata-deploy/local-build/Makefile:219: shim-v2-tarball] Error 2